# Generated by Django 5.1.4 on 2026-02-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
