# Generated by Django 6.0.2 on 2026-03-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='version',
        ),
        migrations.AddField(
            model_name='resume',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
