# Generated by Django 6.0.2 on 2026-02-25 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE_EMPLOYER', 'Approve Employer'), ('BLOCK_USER', 'Block User'), ('UNBLOCK_USER', 'Unblock User'), ('DELETE_JOB', 'Delete Job'), ('REMOVE_SPAM_JOB', 'Remove Spam Job'), ('FLAG_USER', 'Flag User'), ('FLAG_JOB', 'Flag Job'), ('APPROVE_JOB', 'Approve Job'), ('DISABLE_JOB', 'Disable Job')], max_length=50)),
                ('target_job_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
