# Generated by Django 6.0.2 on 2026-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
