# Generated by Django 6.0.2 on 2026-03-02 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_remove_resume_file_hash_remove_resume_version_and_more'),
        ('jobs', '0006_savedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='accounts.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='jobs.job')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
